CREATE SCHEMA capstoneDatabase;

USE capstoneDatabase;

CREATE TABLE User(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_PROVIDER_ID varchar(100) not null,
    USER_EMAIL varchar(100) not null,
    NAME varchar(150) not null,
    USER_PICTURE varchar(512)
);

CREATE TABLE LIST(
    LIST_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    LIST_NAME varchar(100) NOT NULL,
    LIST_DESCRIPTION varchar(300) NOT NULL,
    LIST_IMAGE varchar(512),
    PUBLIC BOOL NOT NULL,
    LIST_LIKES INT NOT NULL,
    LIST_DISLIKES INT NOT NULL
);

CREATE TABLE COMMENT(
    COMMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    LIST_ID INT NOT NULL,
    FOREIGN KEY (LIST_ID) REFERENCES LIST(LIST_ID),
    COMMENT_DESCRIPTION VARCHAR(400) NOT NULL,
    COMMENT_LIKES INT NOT NULL,
    COMMENT_DISLIKES INT NOT NULL
);

CREATE TABLE COMMENT_LIKES( /*this just tracks if a user
                              has already liked a comment or not*/
    COMMENT_ID INT,
    FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(COMMENT_ID),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    PRIMARY KEY (COMMENT_ID,USER_ID),
    IS_LIKED BOOL
    /*if IS_LIKED is null that means its neither liked nor disliked*/
);

CREATE TABLE GAME(
    GAME_ID INT PRIMARY KEY NOT NULL,  /*not auto increment because I'm pulling the
                                        id from the database api*/
    GAME_NAME VARCHAR(150) NOT NULL,
    GAME_RELEASED date NOT NULL,
    GAME_DESCRIPTION VARCHAR(800) NOT NULL,
    GAME_IMAGE VARCHAR(5000)
);

CREATE TABLE LIST_GAME(
    LIST_ID INT,
    FOREIGN KEY (LIST_ID) REFERENCES LIST(LIST_ID),
    GAME_ID INT,
    FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID),
    LIST_GAME_RANK INT NOT NULL,
    LIST_GAME_STATUS VARCHAR(50),
    PRIMARY KEY (LIST_ID,GAME_ID)
)




